"""Routes JSON natives — montées sur /api/app/."""
from django.urls import path
from . import app_api as v

urlpatterns = [
    path('', v.app_catalog, name='app-api-catalog'),
    path('home/', v.app_home, name='app-api-home'),

    path('auth/me/', v.app_me, name='app-api-me'),
    path('auth/login/', v.app_login, name='app-api-login'),
    path('auth/login-by-id/', v.app_login_by_id, name='app-api-login-by-id'),
    path('auth/register/', v.app_register, name='app-api-register'),
    path('auth/logout/', v.app_logout, name='app-api-logout'),
    path('auth/send-otp/', v.app_send_otp, name='app-api-send-otp'),

    path('places/autocomplete/', v.app_places_autocomplete, name='app-api-places-ac'),
    path('places/details/', v.app_places_details, name='app-api-places-details'),
    path('places/recent/', v.app_recent_places, name='app-api-recent-places'),
    path('pricing/estimate/', v.app_pricing_estimate, name='app-api-estimate'),
    path('pricing/route/', v.app_pricing_route, name='app-api-route'),
    path('service-plans/', v.app_service_plans, name='app-api-plans'),

    path('orders/', v.app_orders, name='app-api-orders'),
    path('orders/create/', v.app_create_order, name='app-api-create-order'),
    path('orders/<order_id>/', v.app_order_detail, name='app-api-order'),
    path('orders/<order_id>/status/', v.app_order_status, name='app-api-order-status'),
    path('orders/<order_id>/track/', v.app_order_track, name='app-api-order-track'),
    path('orders/<order_id>/confirm-price/', v.app_confirm_price, name='app-api-confirm-price'),
    path('orders/<order_id>/refuse-price/', v.app_refuse_price, name='app-api-refuse-price'),
    path('orders/<order_id>/cancel/', v.app_cancel_order, name='app-api-cancel'),
    path('orders/<order_id>/phone/', v.app_save_phone, name='app-api-phone'),
    path('orders/<order_id>/payment/init/', v.app_payment_init, name='app-api-pay-init'),
    path('orders/<order_id>/payment/status/', v.app_payment_status, name='app-api-pay-status'),
    path('orders/<order_id>/payment/contract-ack/', v.app_payment_contract_ack, name='app-api-pay-ack'),
    path('orders/<order_id>/update-gps/', v.app_update_gps, name='app-api-gps'),
    path('orders/<order_id>/update-pickup/', v.app_update_pickup, name='app-api-pickup'),
    path('orders/<order_id>/confirm-pickup/', v.app_confirm_pickup, name='app-api-confirm-pickup'),
    path('orders/<order_id>/arrived/', v.app_arrived, name='app-api-arrived'),
    path('orders/<order_id>/rating/', v.app_rating, name='app-api-rating'),
    path('orders/<order_id>/request-return/', v.app_request_return, name='app-api-return'),
    path('orders/<order_id>/client-with-driver/', v.app_client_with_driver, name='app-api-with-driver'),
    path('orders/<order_id>/share/', v.app_share, name='app-api-share'),
    path('orders/<order_id>/sos/', v.app_sos, name='app-api-sos'),
    path('orders/<order_id>/lost-object/', v.app_lost_object, name='app-api-lost'),

    path('chat/<order_id>/', v.app_chat, name='app-api-chat'),
    path('chat/<order_id>/send/', v.app_chat_send, name='app-api-chat-send'),
    path('chat/<order_id>/unread/', v.app_chat_unread, name='app-api-chat-unread'),

    path('account/', v.app_account, name='app-api-account'),
    path('account/update/', v.app_account_update, name='app-api-account-update'),
    path('account/photo/', v.app_account_photo, name='app-api-account-photo'),
    path('account/delete/', v.app_account_delete, name='app-api-account-delete'),
    path('account/stats/', v.app_account_stats, name='app-api-account-stats'),

    path('driver/login/', v.app_driver_login, name='app-api-driver-login'),
    path('driver/logout/', v.app_driver_logout, name='app-api-driver-logout'),
    path('driver/register/', v.app_driver_register, name='app-api-driver-register'),
    path('driver/register/send-otp/', v.app_driver_send_otp, name='app-api-driver-otp'),
    path('driver/register/verify-otp/', v.app_driver_verify_otp, name='app-api-driver-otp-verify'),
    path('driver/home/', v.app_driver_home, name='app-api-driver-home'),
    path('driver/orders/', v.app_driver_orders, name='app-api-driver-orders'),
    path('driver/orders/<order_id>/accept/', v.app_driver_accept, name='app-api-driver-accept'),
    path('driver/orders/<order_id>/status/', v.app_driver_order_status, name='app-api-driver-status'),
    path('driver/orders/<order_id>/cancel/', v.app_driver_cancel, name='app-api-driver-cancel'),
    path('driver/orders/<order_id>/set-coords/', v.app_driver_set_coords, name='app-api-driver-coords'),
    path('driver/orders/<order_id>/extend/', v.app_driver_extend, name='app-api-driver-extend'),
    path('driver/orders/<order_id>/pause/', v.app_driver_pause, name='app-api-driver-pause'),
    path('driver/orders/<order_id>/resume/', v.app_driver_resume, name='app-api-driver-resume'),
    path('driver/orders/<order_id>/share/', v.app_driver_share, name='app-api-driver-share'),
    path('driver/location/', v.app_driver_location, name='app-api-driver-location'),
    path('driver/status/', v.app_driver_online, name='app-api-driver-online'),
    path('driver/active-order/', v.app_driver_active, name='app-api-driver-active'),
    path('driver/stats/', v.app_driver_stats_view, name='app-api-driver-stats'),
    path('driver/wallet/', v.app_driver_wallet, name='app-api-driver-wallet'),
    path('driver/wallet/pay-commission/', v.app_driver_pay_commission, name='app-api-driver-commission'),
    path('driver/wallet/cash-sent/', v.app_driver_cash_sent, name='app-api-driver-cash'),
    path('driver/wallet/withdraw/', v.app_driver_withdraw, name='app-api-driver-withdraw'),
    path('driver/profile/update/', v.app_driver_profile_update, name='app-api-driver-profile'),
]
